window.HKSI_DATA = {
  topics: [
    {
      id: 1,
      code: "T1",
      title: "香港金融业监管概览",
      en: "Regulatory overview",
      verb: "分清谁监管谁",
      sales: true,
      level: "基础底盘",
      weight: "≤7%",
      mockCount: 3,
      focus: ["证监会、金管局、联交所与结算所的角色", "投资者、中介人、主事人与支持服务", "产品、服务与监管边界"],
      trap: "把交易所的市场营运职责与证监会的法定监管职责混在一起。",
      salesHook: "客户问“这是谁批、谁管、谁执行”时，你每天都在用这张监管地图。",
      action: "能用一句话区分 SFC、HKEX、SEHK、HKSCC 与 HKMA。",
    },
    {
      id: 2,
      code: "T2",
      title: "香港法例与《公司条例》原则",
      en: "Hong Kong law & Companies Ordinance",
      verb: "识别法律关系",
      sales: false,
      level: "定义密集",
      weight: "≤7%",
      mockCount: 3,
      focus: ["普通法、衡平法、刑事与民事", "公司类别、股份与债权证", "董事职责、股东权利、决议与清盘"],
      trap: "凭商业常识猜董事或股东的权力，而没有先判断法律身份与程序。",
      salesHook: "公司行动、股东会与董事责任是理解发行人公告的法律底座。",
      action: "把法院、审裁处、仲裁和公司内部决议程序分开。",
    },
    {
      id: 3,
      code: "T3",
      title: "《证券及期货条例》",
      en: "Securities and Futures Ordinance",
      verb: "定位权力与责任",
      sales: true,
      level: "核心骨架",
      weight: "10–17%",
      mockCount: 8,
      focus: ["SFO 各主要部分的功能", "发牌、客户资产、调查、纪律与干预", "市场失当、内幕消息与权益披露"],
      trap: "记住了条例名称，却无法把情境映射到正确的制度、机构或后果。",
      salesHook: "你处理的订单、市场信息与客户沟通，大多能回到 SFO 的一条主线。",
      action: "先画制度地图，再记数字；每个场景回答“谁、对谁、有什么权力”。",
    },
    {
      id: 4,
      code: "T4",
      title: "发牌、注册与附属法例",
      en: "Licensing, registration & subsidiary legislation",
      verb: "判断谁能做什么",
      sales: true,
      level: "Sales 高频",
      weight: "20–27%",
      mockCount: 14,
      focus: ["受规管活动与牌照身份", "负责人员、主管人员、代表与大股东", "客户证券、客户款项、纪录、成交单据与审计"],
      trap: "把公司牌照、个人代表资格、负责人员责任和业务豁免混为一谈。",
      salesHook: "执行订单、给出观点、介绍客户与传递研究，最容易在 Type 1 / Type 4 边界上出题。",
      action: "所有牌照题先拆：主体、活动、是否为业务、是否有豁除。",
    },
    {
      id: 5,
      code: "T5",
      title: "业务操守与客户关系",
      en: "Business conduct & client relations",
      verb: "选出对客户的正确动作",
      sales: true,
      level: "场景高频",
      weight: "15–22%",
      mockCount: 11,
      focus: ["客户协议、适当性与资料披露", "利益冲突、订单处理与客户优先", "专业投资者、复杂产品与责任边界"],
      trap: "看到“机构客户”便默认所有要求都可豁免，忽略题干给出的客户身份与条件。",
      salesHook: "client onboarding、idea pitching、order handling 和 allocation 都是天然场景题。",
      action: "每题按客户身份 → 行为性质 → 是否建议/招揽 → 应做控制判断。",
    },
    {
      id: 6,
      code: "T6",
      title: "业务运作与常规",
      en: "Business operations & practices",
      verb: "找出控制责任",
      sales: true,
      level: "流程型",
      weight: "13–20%",
      mockCount: 9,
      focus: ["管理监督与内部控制", "反洗钱、客户尽职审查与可疑交易", "电子交易、另类交易平台、私隐与业务连续性"],
      trap: "把外包当成责任转移，或只看前台行为而忽略治理、监控与记录。",
      salesHook: "异常资金、第三方付款、电子下单与客户数据，都是一线 sales 会碰到的控制点。",
      action: "先找最终责任人，再看预防、侦测、上报与留痕四层控制。",
    },
    {
      id: 7,
      code: "T7",
      title: "参与香港交易所",
      en: "Participating in Hong Kong exchanges",
      verb: "跑通交易生命周期",
      sales: true,
      level: "实务友好",
      weight: "6–14%",
      mockCount: 6,
      focus: ["HKEX 交易、结算与交收结构", "联交所证券、期权与期货交易", "互联互通、卖空、市场机制与交易成本"],
      trap: "实务经验太强，反而忽略考试指定的制度定义、参与者身份和例外条件。",
      salesHook: "这是最接近你日常盘面的章节，但也是最容易凭经验抢答的章节。",
      action: "按交易前 → 下单 → 成交 → 结算 → 交收画一条流程线。",
    },
    {
      id: 8,
      code: "T8",
      title: "取得公开资本",
      en: "Accessing public capital",
      verb: "区分融资路径与角色",
      sales: true,
      level: "发行人视角",
      weight: "3–10%",
      mockCount: 3,
      focus: ["上市规则与主要参与者", "股本证券、其他上市证券与上市后责任", "收购合并、股份回购、认可产品与另类融资"],
      trap: "把保荐人、整体协调人、包销商、合规顾问与独立财务顾问的角色互换。",
      salesHook: "IPO、配售、公司行动与 takeover 是 equity sales 最容易建立记忆的入口。",
      action: "每个融资场景先标注发行人、投资者、中介角色和监管文件。",
    },
    {
      id: 9,
      code: "T9",
      title: "市场失当与不当交易",
      en: "Market misconduct & improper trading",
      verb: "识别红线与后果",
      sales: true,
      level: "必保分",
      weight: "≤9%",
      mockCount: 3,
      focus: ["内幕交易、虚假交易、操纵价格与披露虚假资料", "未获邀约的造访与不当交易手法", "纪律、民事与刑事执法路径"],
      trap: "只凭结果是否赚钱判断，而忽略信息性质、行为意图、市场表象和责任主体。",
      salesHook: "wall-crossing、market colour、client order 和 personal account dealing 都能变成高质量情境题。",
      action: "对每个行为回答：信息是什么、谁知道、做了什么、影响了谁、可能走哪条执法路径。",
    },
  ],

  blocks: [
    {
      id: "B01",
      order: 1,
      lane: "type1",
      title: "Type 1 发牌边界、人员与跨境营销",
      en: "Licensing perimeter, people & cross-border marketing",
      topics: ["T4"],
      questionIds: ["P1-015", "P1-016", "P1-017", "P1-018", "P1-023", "P1-024", "P1-025", "P1-026"],
      focus: ["受规管活动与机构身份", "持牌代表、负责人员与 fit and proper", "附带豁免、active marketing 与跨境边界"],
      outcome: "看到一个 sales 行为，能按主体、活动、是否为业务、牌照或豁免逐层判断。",
      why: "先练你岗位最直接的规则入口：谁可以在什么条件下做什么。",
    },
    {
      id: "B02",
      order: 2,
      lane: "type1",
      title: "客户准入、招揽、适当性与复杂产品",
      en: "Client admission, solicitation & suitability",
      topics: ["T5"],
      questionIds: ["P1-029", "P1-030", "P1-031", "P1-037", "P1-039"],
      focus: ["总体操守与 KYC", "事实资料、建议与招揽", "复杂产品与非亲身开户"],
      outcome: "接单前能判断客户资料是否充分、沟通是否触发适当性，以及产品能否销售。",
      why: "机构客户不等于全面豁免；先把 onboarding 与建议边界练清。",
    },
    {
      id: "B03",
      order: 3,
      lane: "type1",
      title: "订单执行、利益冲突、分配与投诉",
      en: "Execution, conflicts, allocation & complaints",
      topics: ["T5"],
      questionIds: ["P1-032", "P1-033", "P1-034", "P1-035", "P1-036", "P1-038"],
      focus: ["best execution 与客户优先", "facilitation 冲突与部分成交分配", "指示留痕、争议调查与投诉"],
      outcome: "从接单到投诉，能维持公平执行、冲突披露、可靠分配和完整证据链。",
      why: "这是 institutional equity sales 最贴近日常、也最容易凭经验抢答的一块。",
    },
    {
      id: "B04",
      order: 4,
      lane: "type1",
      title: "持牌法团稳健经营：资产、纪录与资本",
      en: "Firm safeguards: assets, records & capital",
      topics: ["T4"],
      questionIds: ["P1-019", "P1-020", "P1-021", "P1-022", "P1-027", "P1-028"],
      focus: ["客户款项、客户证券与交易纪录", "OTC post-trade 责任", "财政资源与核数师报告"],
      outcome: "识别客户资产、纪录、资本和法定报告的关键责任及升级点。",
      why: "把前台动作与法团层面的中后台保障连起来。",
    },
    {
      id: "B05",
      order: 5,
      lane: "type1",
      title: "AML、异常资金、客户数据与税务透明",
      en: "AML, funds, client data & tax transparency",
      topics: ["T6"],
      questionIds: ["P1-041", "P1-042", "P1-043", "P1-046", "P1-047"],
      focus: ["风险为本方法与第三方付款红旗", "STR、tipping-off 与升级", "客户资料使用、保密与 CRS"],
      outcome: "识别资金及资料红旗，并区分 AML、客户保密、私隐和 CRS 的责任。",
      why: "把资金与数据责任集中训练，不再与算法和系统事故混成一组。",
    },
    {
      id: "B06",
      order: 6,
      lane: "type1",
      title: "系统治理、电子交易与业务韧性",
      en: "Systems, electronic trading & resilience",
      topics: ["T6"],
      questionIds: ["P1-040", "P1-044", "P1-045", "P1-048"],
      focus: ["外判不转移责任", "算法交易与另类流动性平台", "系统中断与业务连续性"],
      outcome: "判断供应商、算法、暗池或系统事故下，法团仍须承担哪些控制责任。",
      why: "把电子执行和 operational resilience 从 AML 中独立出来。",
    },
    {
      id: "B07",
      order: 7,
      lane: "type1",
      title: "市场基础设施、互联互通与交易所产品",
      en: "Market infrastructure, Connect & exchange products",
      topics: ["T7"],
      questionIds: ["P1-049", "P1-050", "P1-051", "P1-052", "P1-053", "P1-054"],
      focus: ["交易与结算角色", "互联互通与期权庄家", "持仓汇报与上市衍生产品"],
      outcome: "识别交易、结算、跨境准入、衍生品控制及交易所产品风险。",
      why: "实务最熟，但答题必须切回 HKSI 的参与者名称和制度口径。",
    },
    {
      id: "B08",
      order: 8,
      lane: "type1",
      title: "内幕信息与市场失当红线",
      en: "Inside information & market misconduct",
      topics: ["T9"],
      questionIds: ["P1-058", "P1-059", "P1-060"],
      focus: ["MNPI 泄露", "虚假交易", "操纵收市价"],
      outcome: "能立即识别三类高风险场景，并作出停止、拒绝、留痕和升级。",
      why: "corporate access、market colour 与客户订单都可能触发这条前线红线。",
    },
    {
      id: "B09",
      order: 9,
      lane: "type1",
      title: "香港证券监管地图",
      en: "Hong Kong securities regulatory map",
      topics: ["T1", "T3"],
      questionIds: ["P1-001", "P1-002", "P1-003", "P1-007", "P1-008"],
      focus: ["SFC、HKMA、HKEX、SEHK 与结算所", "银行、持牌法团与市场机构", "监管目标、权力与执法边界"],
      outcome: "看到机构或监管行动时，能判断谁监管、监管什么、权力边界在哪里。",
      why: "这是一线判断的地图层；独立成块，避免和具体牌照规则混背。",
    },
    {
      id: "B10",
      order: 10,
      lane: "exam",
      title: "SFO 法定产品制度与投资者保护",
      en: "SFO product regime & investor protection",
      topics: ["T3"],
      questionIds: ["P1-009", "P1-010", "P1-011", "P1-012", "P1-014"],
      focus: ["公开推广限制与 OFC", "监管复核与投资者赔偿", "证监会介入措施"],
      outcome: "判断产品能否推广、客户受什么保护，以及监管决定和介入的法定路径。",
      why: "作为 Paper 1 制度补齐，集中比较容易混淆的法定机制。",
    },
    {
      id: "B11",
      order: 11,
      lane: "exam",
      title: "公司法人、董事责任与治理",
      en: "Corporate personality, directors & governance",
      topics: ["T2"],
      questionIds: ["P1-004", "P1-005", "P1-006"],
      focus: ["独立法人地位", "董事职责与公司机会", "董事会、股东与少数股东保护"],
      outcome: "区分公司、股东和董事责任，并识别公司机会与治理冲突。",
      why: "题量不高但定义容易丢分，作为短板块一次练透。",
    },
    {
      id: "B12",
      order: 12,
      lane: "exam",
      title: "上市公司披露、上市规则与交易事件",
      en: "Issuer disclosure, Listing Rules & transactions",
      topics: ["T3", "T8"],
      questionIds: ["P1-013", "P1-055", "P1-056", "P1-057"],
      focus: ["内幕消息、内幕交易限制与权益披露", "上市规则与保荐人尽调", "关连交易与须予公布交易"],
      outcome: "看懂上市公司信息责任，以及 IPO、收购和关连交易为何触发公告、审批或限制。",
      why: "把发行人披露与上市事件连学，避免 P1-013 孤立在笼统的 SFO 板块。",
    },
  ],

  lens: [
    {
      label: "客户要你立即下单",
      title: "执行 vs 建议",
      topic: "T4 · T5",
      body: "先判断你在传达/执行指示，还是主动作出建议或招揽；考试会用同一句对话测试不同受规管活动与操守要求。",
      trap: "“我是 sales”不是答案，活动本身才是。",
    },
    {
      label: "你拿到公司未公开数字",
      title: "market colour vs inside information",
      topic: "T3 · T9",
      body: "不要从消息真假或是否利好开始；先判断是否具体、未公开、价格敏感，以及你和客户随后采取了什么行动。",
      trap: "消息来自客户或管理层，都不自动改变其性质。",
    },
    {
      label: "机构客户说不需要保护",
      title: "专业投资者不是一句话",
      topic: "T5",
      body: "题目会区分客户类别、是否完成相关程序，以及哪些要求可被豁免。不要把 institutional 与全面豁免画等号。",
      trap: "看到“基金”就跳到豁免，是典型抢答。",
    },
    {
      label: "大单、交叉盘与 allocation",
      title: "订单公平与冲突",
      topic: "T5 · T7",
      body: "把客户优先、及时公平执行、利益冲突、聚合/分配和留痕分开判断；不要只看成交结果是否有利。",
      trap: "好价格不能补救不公平的过程。",
    },
    {
      label: "IPO / placement 讨论",
      title: "发行角色不能串台",
      topic: "T8",
      body: "保荐、协调、包销、合规与独立意见承担不同功能。先识别交易阶段，再选角色。",
      trap: "同一家机构可能戴多顶帽子，但每顶帽子的职责仍不同。",
    },
    {
      label: "第三方付款或异常资金",
      title: "前台也在 AML 控制链上",
      topic: "T6",
      body: "识别异常、升级、避免 tipping-off，并确保记录；不能因为有 compliance 团队就把一线责任视为零。",
      trap: "外包或转交不等于责任消失。",
    },
  ],

  updates: [
    {
      topic: "T1",
      title: "机构名称已更新",
      body: "金银业贸易场已改称香港黄金交易所。旧题或旧笔记中的旧称只作为识别别名，不再作为当前答题用语。",
      action: "先改名，再记监管角色",
    },
    {
      topic: "T2",
      title: "《公司条例》2025 修订",
      body: "v3.5 纳入两项 2025 年公司法修订相关更新；遇到旧版公司程序总结时，先回到现行手册复核。",
      action: "旧版程序题一律复核",
    },
    {
      topic: "T5",
      title: "开户方式口径更新",
      body: "证监会可接受的开户方式资料已更新。考试会从客户身份、验证步骤和控制责任切入，不要只背渠道名称。",
      action: "按身份—验证—留痕作答",
    },
    {
      topic: "T7",
      title: "每周期权与持仓限额",
      body: "更新每周期权相关庄家获批范围，并更新恒指、国指及恒生科技指数相关持仓限额资料；易变数字只认 v3.5。",
      action: "把易变数字单独回炉",
    },
    {
      topic: "T8",
      title: "本版最大更新区",
      body: "覆盖无纸证券市场、上市及 GEM 改革、IPO 定价和公众持股量、收购回购，以及代币化／数码证券与虚拟资产相关产品。",
      action: "优先做新概念辨析题",
    },
  ],

  terms: [
    ["持牌法团", "持牌法團", "licensed corporation", "公司层面的牌照主体，不等于个人代表"],
    ["持牌代表", "持牌代表", "licensed representative", "代表隶属持牌法团从事获准活动"],
    ["负责人员", "負責人員", "responsible officer", "负责监督持牌法团某类受规管活动"],
    ["注册机构", "註冊機構", "registered institution", "通常指获金管局监管并向 SFC 注册的认可财务机构"],
    ["主管人员", "主管人員", "executive officer", "注册机构体系中的关键监督身份"],
    ["受规管活动", "受規管活動", "regulated activity", "先识别活动，再看主体与豁除"],
    ["证券交易", "證券交易", "dealing in securities", "重点看是否订立、要约、诱使或传达交易安排"],
    ["就证券提供意见", "就證券提供意見", "advising on securities", "建议/分析的事实情境比职位名称更重要"],
    ["专业投资者", "專業投資者", "professional investor", "类别、程序与可豁免要求必须分别判断"],
    ["适当性", "合適性", "suitability", "建议或招揽情境下的核心客户保护概念"],
    ["客户款项", "客戶款項", "client money", "与公司自有资金分隔、指定账户和处理流程相关"],
    ["客户证券", "客戶證券", "client securities", "关注持有、存放、授权与再质押边界"],
    ["内幕消息", "內幕消息", "inside information", "具体、未公开且对价格有重大影响的资料"],
    ["内幕交易", "內幕交易", "insider dealing", "信息、关连人士、交易或促成行为要素缺一不可"],
    ["虚假交易", "虛假交易", "false trading", "制造虚假或误导性的活跃交易或市场表象"],
    ["操纵价格", "操縱價格", "price rigging", "围绕人为维持、提高、降低或稳定价格的行为判断"],
    ["市场失当行为审裁处", "市場失當行為審裁處", "Market Misconduct Tribunal", "市场失当民事制度的重要机构"],
    ["证券及期货事务上诉审裁处", "證券及期貨事務上訴審裁處", "Securities and Futures Appeals Tribunal", "复核指定监管决定，勿与 MMT 混淆"],
    ["中央结算系统", "中央結算系統", "CCASS", "证券结算、交收与托管基础设施"],
    ["未获邀约的造访", "未獲邀約的造訪", "unsolicited call / visit", "留意题目所述接触方式、地点、对象与例外"],
  ],

  sources: [
    {
      id: "O1",
      title: "HKSI LE 官方概览与考试规格",
      kind: "官方现行",
      status: "green",
      detail: "确认 Paper 1 为 60 道 MCQ、90 分钟、70% 及格，考试题目语言为英文和繁体中文。",
      url: "https://www.hksi.org/qualification/examinations/licensing-examination-for-securities-and-futures-intermediaries/overview/",
      tags: "60 90 70 exam overview",
    },
    {
      id: "O2",
      title: "Paper 1 v3.5 官方大纲",
      kind: "官方现行",
      status: "green",
      detail: "九大 Topic 与 Expected Learning Outcomes；自 2026-06-30 起生效。",
      url: "https://www.hksi.org/media/8902/p1-syllabus_eng-v35_clean.pdf",
      tags: "v3.5 syllabus topic learning outcome",
    },
    {
      id: "O3",
      title: "HKSI Study Guide 更新页",
      kind: "官方现行",
      status: "green",
      detail: "v3.5 适用于 2026-06-30 起的考试；v3.4.2 仅适用至 2026-06-29（含）。",
      url: "https://www.hksi.org/en/qualification/examinations/licensing-examination-for-securities-and-futures-intermediaries/updating-your-study-guides/",
      tags: "version 3.5 3.4.2 update",
    },
    {
      id: "O4",
      title: "HKSI 考试准备指引",
      kind: "官方现行",
      status: "green",
      detail: "监管类试卷参考自学 55–85 小时；MCQ 测试记忆、理解、应用与比较，需留意 ONE / MOST LIKELY / INCORRECT / 组合题题干。",
      url: "https://www.hksi.org/en/qualification/examinations/licensing-examination-for-securities-and-futures-intermediaries/guidelines-for-examination-preparation/",
      tags: "study hours MCQ strategy",
    },
    {
      id: "L0",
      title: "温习手册最新.pdf（v3.5，440 页）",
      kind: "本地官方现行",
      status: "green",
      detail: "ZIP 独有，封面注明 2026 年 4 月 v3.5、2026-06-30 起生效；本站章节比重、认知层级与更新风险均以此为底座。原 PDF 未上传本站。",
      tags: "zip current official v3.5 440 traditional",
    },
    {
      id: "L1",
      title: "P1 v3.4.2 chi full 简体.docx",
      kind: "本地过期资料",
      status: "red",
      detail: "5710 段、69 个表格、九章结构完整；只用于框架与术语理解，不用作当前易变规则的最终依据。未上传本站。",
      tags: "docx simplified 3.4.2 local",
    },
    {
      id: "L2",
      title: "P1 v3.4.2 繁体 PDF（437 页）",
      kind: "本地过期资料",
      status: "red",
      detail: "适合繁体术语识别，但版本已过期。未上传本站。",
      tags: "traditional pdf 437 3.4.2 local",
    },
    {
      id: "L3",
      title: "P1 v3.4.2 English PDF（436 页）",
      kind: "本地过期资料",
      status: "red",
      detail: "适合英文概念对照，但版本已过期。未上传本站。",
      tags: "english pdf 436 3.4.2 local",
    },
    {
      id: "L4",
      title: "第一至第九章课程 PDF",
      kind: "本地辅助资料",
      status: "amber",
      detail: "共 313 页、以课程视频截图为主，适合低摩擦复习与示意图回看；不是可搜索的权威文本，也不作为规则更新来源。未上传本站。",
      tags: "chapter screenshot course bilibili local",
    },
    {
      id: "L5",
      title: "HKSI P1 补充题库（文件名标注 233 页）",
      kind: "待核验题库",
      status: "amber",
      detail: "三个导出批次拼接，存在大量重复、截断和解析质量问题；只观察题型与错因，本站不复制原题。",
      tags: "question bank 233 unverified local",
    },
    {
      id: "L6",
      title: "官方练习题1（23 页，2006 年历史题）",
      kind: "历史题型样本",
      status: "red",
      detail: "只用于观察传统 MCQ 版式和反向题干；法规内容与答案不应直接用于当前考试。未上传本站。",
      tags: "official historical 2006 practice local",
    },
    {
      id: "L7",
      title: "官方练习题2（63 页，2023 样题）",
      kind: "官方题型样本",
      status: "amber",
      detail: "英文 + 繁体、60 题、一题一页、末页答案表；适合学习界面与题干结构，不公开复制题目，也不当作 v3.5 规则底座。",
      tags: "official practice pending local",
    },
    {
      id: "L8",
      title: "HKSI.zip（约 182 MB）",
      kind: "本地容器",
      status: "green",
      detail: "完整性测试通过；除目录副本外，关键新增是当前 v3.5 官方繁体手册与一份简体 v3.4.2 PDF。ZIP 本身不提交 GitHub。",
      tags: "zip archive local copyright",
    },
  ],
};
