window.HKSI_QUESTIONS = [
  {
    id: "P1-001",
    topic: 1,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "single",
    stem: "一家香港银行从事证券交易业务，而一家非银行证券公司也从事同类业务。以下哪项最准确？",
    options: ["两者均只由香港金融管理局监管", "证券公司通常由证监会发牌；银行作为注册机构由金管局负责日常前线监管，并处于证监会的证券监管框架内", "两者均只受香港交易所监管", "银行从事证券业务无需受到证券监管"],
    answer: 1,
    explanation: "非银行中介通常由证监会发牌；认可财务机构以注册机构身份从事受规管活动，金管局承担前线监管职能，证监会仍负责相关证券监管标准。",
    trap: "把银行业监管机构与证券业务的监管框架混为一谈。",
    salesHook: "Institutional sales 经常同时覆盖银行客户与券商客户，必须区分 registered institution 与 licensed corporation。",
  },
  {
    id: "P1-002",
    topic: 1,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "incorrect",
    stem: "关于 HKEX、SEHK、认可结算所与证监会，以下哪项不正确？",
    options: ["HKEX 集团营运香港的交易及结算基础设施", "SEHK 可依据其规则监管上市及交易参与者，并受证监会监督", "认可结算所负责相应市场的结算、交收及风险管理安排", "HKEX 可以代替证监会向证券公司签发《证券及期货条例》下的法团牌照"],
    answer: 3,
    explanation: "证券中介的法团牌照由证监会负责，HKEX 的交易所及结算所职能不能取代证监会的发牌权。",
    trap: "把交易所自律监管权误认为法定发牌权。",
    salesHook: "面对客户问及 broker status 时，应查证 SFC 公开纪录，而非只看其是否为交易所参与者。",
  },
  {
    id: "P1-003",
    topic: 1,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "single",
    stem: "关于香港贵金属市场机构的最新名称，以下哪项正确？",
    options: ["金银业贸易场已改名为香港黄金交易所；香港黄金交易所是香港唯一的现货黄金及白银交易所", "香港黄金交易所是 SEHK 的另一个名称", "香港黄金交易所负责向证券经纪发出第1类牌照", "金银业贸易场已改名为香港期货交易所"],
    answer: 0,
    explanation: "Version 3.5 明确金银业贸易场已改名为香港黄金交易所；香港黄金交易所是香港唯一的现货黄金及白银交易所。它不是 SEHK、HKFE 或证监会。",
    trap: "把名称相近的商品、证券和期货交易机构混为一谈。",
    salesHook: "覆盖贵金属相关客户或产品时，使用当前机构名称并识别其实际市场职能。",
  },

  {
    id: "P1-004",
    topic: 2,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "incorrect",
    stem: "关于香港公司的独立法人地位，以下哪项不正确？",
    options: ["公司可持有自己的资产", "公司可用自己的名义订立合约及诉讼", "股东仅因持有股份便自动对公司所有债务承担无限个人责任", "公司责任与董事或股东责任原则上需要分别分析"],
    answer: 2,
    explanation: "公司具有独立法人地位；股东不会仅因持股而自动承担公司全部债务，但欺诈、担保或其他法定情形须另行分析。",
    trap: "把公司债务与股东个人债务直接等同。",
    salesHook: "分析 issuer、母公司及大股东的责任时不能只凭集团品牌判断。",
  },
  {
    id: "P1-005",
    topic: 2,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "某董事因职务得知公司正考虑收购一项资产，随后计划以个人名义抢先买入该资产。按董事职责，最合适的处理是什么？",
    options: ["只要个人资金充足即可进行", "避免擅自利用公司机会，并作出完整披露及遵循适用的批准和回避程序", "在交易完成后才通知公司即可", "只要公司暂未签署合约便不存在职责问题"],
    answer: 1,
    explanation: "董事须为公司利益行事，并妥善处理利益冲突及公司机会；未签约不代表职责尚未产生。",
    trap: "误以为只有已签署交易才会触发董事职责。",
    salesHook: "覆盖上市公司管理层交易及 corporate access 时有助识别利益冲突。",
  },
  {
    id: "P1-006",
    topic: 2,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于公司治理：I. 公司章程是公司内部治理的重要文件；II. 董事会权力受《公司条例》及章程约束；III. 股东可通过适当决议行使法定或章程赋予的权力；IV. 法律提供若干机制保护少数股东。哪些陈述正确？",
    options: ["I、II", "II、III", "I、III、IV", "I、II、III、IV"],
    answer: 3,
    explanation: "四项均属于公司治理的基本框架。",
    trap: "把董事会权力理解为完全不受股东或公司法约束。",
    salesHook: "阅读上市公司公告与股东大会文件时的基础框架。",
  },

  {
    id: "P1-007",
    topic: 3,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "single",
    stem: "以下哪项最符合证监会在《证券及期货条例》下的监管目标？",
    options: ["维持市场公平、有秩序及透明，并协助保障投资公众", "保证所有上市证券价格上涨", "替市场参与者承担投资损失", "直接经营所有持牌法团"],
    answer: 0,
    explanation: "证监会目标包括维持市场质量、保障投资者、降低系统性风险及打击违法失当行为，而非保证收益。",
    trap: "把监管者的投资者保障职责误解为回报保证。",
    salesHook: "客户质疑监管作用时可区分市场诚信与投资表现。",
  },
  {
    id: "P1-008",
    topic: 3,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "incorrect",
    stem: "关于证监会的调查及执法权力，以下哪项不正确？",
    options: ["证监会可在法定条件下要求提供资料或文件", "证监会可对受规管人士展开纪律程序", "证监会可不受任何法定程序限制而随意进入任何私人处所搜查", "涉嫌刑事事项可按适用程序交由刑事检控处理"],
    answer: 2,
    explanation: "调查权属于法定权力，必须依条例及适用程序行使，并非不受限制。",
    trap: "把强制调查权误解为无限权力。",
    salesHook: "发生录音、通讯或订单调查时，销售应立即交由合规及法律团队处理。",
  },
  {
    id: "P1-009",
    topic: 3,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "销售团队拟向香港公众推广一只尚未在港获认可的海外基金。最适当的监管处理是什么？",
    options: ["只要基金在海外合法便可公开推广", "暂停推广并评估《证券及期货条例》第IV部、适用的招股章程或认可要求及任何具体豁免", "在广告加上高风险字样即可", "把材料称为教育资料便必然不受规管"],
    answer: 1,
    explanation: "向香港公众作出投资要约或发出推广材料可能触发认可、招股章程及广告限制；标签不能取代实质分析。",
    trap: "认为海外批准或免责声明自动满足香港公开发售要求。",
    salesHook: "直接对应 fund distribution 与 client blast 的发布前审查。",
  },
  {
    id: "P1-010",
    topic: 3,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "single",
    stem: "以下哪项最能描述开放式基金型公司 OFC？",
    options: ["具独立法人地位、资本可随认购赎回变动，并受专门基金监管框架约束的公司型投资基金", "只能经营实体贸易的普通私人公司", "不具有任何法人地位的合伙企业", "由交易所保证本金的存款产品"],
    answer: 0,
    explanation: "OFC 是公司型集体投资计划，具有可变资本等基金特征，并受到 SFO、OFC 规则及相关守则规管。",
    trap: "只看到公司二字便把 OFC 当作普通营运公司。",
    salesHook: "销售公司型基金时可与 unit trust 结构区分。",
  },
  {
    id: "P1-011",
    topic: 3,
    difficulty: "较难",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于证券及期货事务上诉审裁处 SFAT：I. 可复核法例指定的证监会等监管决定；II. 可依其法定权限确认、更改或撤销有关决定；III. 负责对市场失当作刑事定罪；IV. 负责日常处理交易所结算。哪些陈述正确？",
    options: ["I、II", "I、III", "II、IV", "I、II、III、IV"],
    answer: 0,
    explanation: "SFAT 是复核指定监管决定的法定审裁机构，不是刑事法院或结算所。",
    trap: "把 SFAT 与 MMT、法院或 HKEX 结算职能混淆。",
    salesHook: "牌照或纪律决定出现争议时有助区分 review channel。",
  },
  {
    id: "P1-012",
    topic: 3,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "most_likely",
    stem: "某客户因市场价格下跌而亏损，要求投资者赔偿基金全额补偿。哪项回应最准确？",
    options: ["所有证券价格损失均由基金承担", "该基金只针对法定范围内、符合资格并与有关中介违责相关的损失，不是市场亏损保险", "只要客户是个人便自动获赔", "客户只需证明证券曾在香港交易便必然获赔"],
    answer: 1,
    explanation: "投资者赔偿制度是有范围和资格条件的法定安全网，不承保普通市场风险。",
    trap: "把 investor compensation 与本金保证混为一谈。",
    salesHook: "客户问券商倒闭风险时，避免把赔偿基金描述为无限保障。",
  },
  {
    id: "P1-013",
    topic: 3,
    difficulty: "较难",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于上市法团的内幕消息披露及权益披露：I. 上市法团须在知悉内幕消息后按法定框架及时披露，除非适用安全港；II. 管有内幕消息的人仍须考虑内幕交易限制；III. 大股东及董事的权益披露属于另一套法定责任；IV. 所有未经证实的市场传闻都自动构成内幕消息。哪些陈述正确？",
    options: ["I", "I、II", "I、II、III", "II、III、IV"],
    answer: 2,
    explanation: "内幕消息披露、内幕交易及权益披露相互关联但属于不同义务；传闻是否构成内幕消息须按事实及法定定义判断。",
    trap: "把任何传闻自动等同 inside information，或把发行人披露义务与个人交易限制混为一项。",
    salesHook: "Sales 与 corporate access 处理未公开信息时的核心边界。",
  },
  {
    id: "P1-014",
    topic: 3,
    difficulty: "较难",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "证监会有合理理由担心某持牌法团的经营方式可能危及客户资产。以下哪项最准确？",
    options: ["证监会必须等待刑事定罪后才可采取任何行动", "证监会可在《证券及期货条例》的法定条件和程序下考虑采取介入或限制措施，以保障客户和市场", "证监会可永久没收任何无关人士的资产而无需程序", "只有 HKEX 可处理持牌法团的客户资产风险"],
    answer: 1,
    explanation: "SFO 赋予证监会在法定条件下采取介入及限制措施的权力；这些监管措施不以先有刑事定罪为必要，但必须按法定程序行使。",
    trap: "把监管介入、刑事检控和无条件资产没收混为一谈。",
    salesHook: "当券商出现资本、托管或经营风险时，销售须理解监管限制可能先于刑事程序。",
  },

  {
    id: "P1-015",
    topic: 4,
    difficulty: "基础",
    cognitiveLevel: 2,
    type: "single",
    stem: "销售人员接受机构客户的香港股票买卖指示，并安排成交，最直接涉及哪类受规管活动？",
    options: ["第1类：证券交易", "第4类：就证券提供意见", "第6类：就机构融资提供意见", "第9类：资产管理"],
    answer: 0,
    explanation: "接受及执行证券买卖指示通常属于第1类证券交易；若另有独立意见服务，还要分析第4类及豁免。",
    trap: "把所有销售沟通一律归入证券意见，而忽略实际交易活动。",
    salesHook: "Institutional equity sales 的基本牌照口径。",
  },
  {
    id: "P1-016",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "most_likely",
    stem: "一家认可财务机构拟在香港开展证券交易业务。其最可能采用的监管身份是什么？",
    options: ["由证监会发牌的普通合伙", "就相关受规管活动向证监会注册的注册机构，并由金管局作前线监管", "只成为交易所上市发行人即可", "无需任何证券业务注册"],
    answer: 1,
    explanation: "认可财务机构以 registered institution 身份从事获注册的受规管活动。",
    trap: "将银行牌照本身视为证券业务授权。",
    salesHook: "分析银行经纪或 private bank 的牌照身份。",
  },
  {
    id: "P1-017",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于持牌代表 LR 与负责人员 RO：I. LR 只可代表其获隶属的主事人进行获准活动；II. RO 直接监督法团的受规管活动；III. 法团须保持适当的 RO 监督安排；IV. 所有纯行政后勤员工都必然需要 LR 牌照。哪些陈述正确？",
    options: ["I、II", "II、III", "I、II、III", "I、III、IV"],
    answer: 2,
    explanation: "I 至 III 正确；纯行政职能是否属于 regulated function 要按实质判断，并非所有后勤员工必然持牌。",
    trap: "按职位名称而非实际职能判断牌照需要。",
    salesHook: "团队分工、coverage support 与 execution staff 的牌照边界。",
  },
  {
    id: "P1-018",
    topic: 4,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "incorrect",
    stem: "关于 fit and proper 要求，以下哪项不正确？",
    options: ["会考虑胜任能力、诚信、财政稳健及声誉等因素", "适用于个人及法团的申请和持续监管", "重大纪律或诚信事件可能影响持续适当人选状态", "牌照一经发出，适当人选要求便不再相关"],
    answer: 3,
    explanation: "Fit and proper 是持续要求，不只在申请时评估。",
    trap: "把牌照当成永久且不受持续审视的资格。",
    salesHook: "个人行为、外部调查或财务问题均可能影响牌照状态。",
  },
  {
    id: "P1-019",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "运营人员发现客户款项被转入法团自有营运账户，只因交易员称这样交收较方便。最适当的处理是什么？",
    options: ["机构客户已知情便可继续", "立即停止不当使用、核对及隔离客户款项，并按内部升级和适用规则处理", "月底再统一调回即可", "把款项记作临时收入即可"],
    answer: 1,
    explanation: "客户款项须按法定方式持有、隔离及记录；操作便利不能凌驾客户资产规则。",
    trap: "把短期挪用视为无害的 operational shortcut。",
    salesHook: "大额机构交收更容易造成显著 client money 风险。",
  },
  {
    id: "P1-020",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "关于客户证券，哪项原则最准确？",
    options: ["中介使用、质押或转移客户证券须有适用法律基础及必要授权，并保持妥善保管和记录", "只要证券可在市场交易，中介可自由用于自身融资", "专业投资者的证券自动成为中介资产", "客户证券无需与中介记录区分"],
    answer: 0,
    explanation: "客户证券受专门保管、授权、使用及记录规定约束，不会因客户类型或证券流通性而自动变为中介资产。",
    trap: "把 custody control 与资产所有权混淆。",
    salesHook: "Prime brokerage、stock borrow 与 settlement instruction 的基础风险。",
  },
  {
    id: "P1-021",
    topic: 4,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "single",
    stem: "合约单、账户结单及交易记录的主要监管作用是什么？",
    options: ["只用于市场推广", "只在客户投诉后才需要制作", "向客户提供交易资料，并形成可核查的账目及审计轨迹", "替代所有客户协议和风险披露"],
    answer: 2,
    explanation: "这些文件支持客户透明度、账目核对、监管检查和审计，并不能替代其他合规文件。",
    trap: "把记录保存当成纯行政事项。",
    salesHook: "订单争议时，time stamp、allocation 与 contract note 是关键证据。",
  },
  {
    id: "P1-022",
    topic: 4,
    difficulty: "较难",
    cognitiveLevel: 2,
    type: "incorrect",
    stem: "关于场外衍生工具的汇报与结算责任，以下哪项不正确？",
    options: ["两类责任的政策目的并不相同", "是否适用须按交易、产品及对手方等法定条件分析", "交易一经向资料储存库汇报，便自动视为已履行所有中央结算责任", "负有适用汇报或结算责任的法团须保存足够资料，以支持适用性判断及履责"],
    answer: 2,
    explanation: "汇报与中央结算是不同监管义务；满足一项不等于自动满足另一项。",
    trap: "把 reporting 和 clearing 当成同一动作。",
    salesHook: "机构客户做 equity swaps 或其他 OTC 产品时的 post-trade gate。",
  },
  {
    id: "P1-023",
    topic: 4,
    difficulty: "较难",
    cognitiveLevel: 3,
    type: "combination",
    stem: "关于第1类持牌法团可能适用的附带豁免：I. 完全附带于证券交易业务的证券意见可能无需另持第4类牌照；II. 独立收费及独立经营的意见服务不当然属于附带业务；III. 只要内部称为 sales support 便一定获豁免；IV. 应按服务实质及整体业务安排判断。哪些陈述正确？",
    options: ["I、II", "I、III", "I、II、IV", "II、III、IV"],
    answer: 2,
    explanation: "附带豁免取决于意见是否真正从属并完全附带于第1类业务，不能仅靠内部标签。",
    trap: "把 wholly incidental 误解为 sales 团队作出的任何意见。",
    salesHook: "最贴近 institutional sales 的 Type 1/Type 4 边界。",
  },
  {
    id: "P1-024",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于持牌法团的负责人员安排：I. 每项申请进行的受规管活动通常须有不少于两名负责人员直接监督；II. 每项有关活动须有至少一名负责人员可随时履行监督职责；III. 至少一名有关负责人员须为法团的执行董事；IV. 所有负责人员必须每天同时身处同一办公室。哪些陈述正确？",
    options: ["I、II", "I、III", "I、II、III", "II、III、IV"],
    answer: 2,
    explanation: "I 至 III 属负责人员架构的基本要求；监管重点是有效及持续监督，并非要求所有负责人员每天同时在同一地点。",
    trap: "记住人数却忽略可用性及执行董事要求，或把可用性误解为必须实体同场。",
    salesHook: "团队扩张、休假和跨境 coverage 安排均要确保 RO supervision 不失效。",
  },
  {
    id: "P1-025",
    topic: 4,
    difficulty: "较难",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "一家海外券商没有香港牌照，却由境外团队持续向香港公众主动推广一项若在香港提供会构成受规管活动的服务。最合适的判断是什么？",
    options: ["团队在境外，所以香港牌照问题必然不存在", "主动向香港公众推广有关服务可能触发香港发牌规定，应先作监管范围分析", "只要网站服务器不在香港便获豁免", "只有客户实际亏损后才需考虑牌照"],
    answer: 1,
    explanation: "《证券及期货条例》的 active marketing 规定可涵盖由香港境外主动向香港公众推广有关服务的情况，不能只看人员或服务器所在地。",
    trap: "把跨境提供服务的位置当成唯一牌照连接点。",
    salesHook: "跨境 client outreach、全球网站和境外 desk referral 的关键 gate。",
  },
  {
    id: "P1-026",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "combination",
    stem: "以下受规管活动配对：I. 第7类——提供自动化交易服务；II. 第8类——证券保证金融资；III. 第9类——资产管理；IV. 第4类——提供客户结算服务。哪些配对正确？",
    options: ["I、II", "I、II、III", "II、IV", "I、III、IV"],
    answer: 1,
    explanation: "I 至 III 正确；第4类是就证券提供意见，不是提供客户结算服务。",
    trap: "只凭编号猜测活动名称。",
    salesHook: "新产品或服务上线前先识别 activity perimeter。",
  },
  {
    id: "P1-027",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "关于持牌法团的财政资源责任，哪项最准确？",
    options: ["只需在申请牌照当日符合规定", "只要母公司有资金，法团无需自行监察", "法团须持续监察其财政资源状况，并按适用规定处理不足或预警情况", "年度审计可替代日常资本监察"],
    answer: 2,
    explanation: "财政资源是持续责任，法团需要有日常监察及升级机制；集团支持或年度审计不能取代法团自身义务。",
    trap: "把 capital compliance 当成年度或一次性检查。",
    salesHook: "券商资本压力可能影响承接 facilitation、保证金及客户资产安排。",
  },
  {
    id: "P1-028",
    topic: 4,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "外聘核数师在审计中发现可能严重影响客户资产保障的违规事项。哪项最准确？",
    options: ["核数师在任何情况下都只能向管理层报告", "核数师可能负有向证监会作出法定报告的责任；管理层不能以保密为由要求其忽略有关责任", "年度报告尚未发表，所以事项必然无需处理", "客户是专业投资者便不存在审计责任"],
    answer: 1,
    explanation: "SFO 及附属法例可对中介核数师设定特定报告责任；审计并不只服务管理层，也不能由客户分类排除。",
    trap: "把一般商业保密义务误认为可凌驾法定报告责任。",
    salesHook: "客户资产或账目异常必须及时升级，不能等年报流程结束。",
  },

  {
    id: "P1-029",
    topic: 5,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "single",
    stem: "以下哪项最符合《操守准则》的总体要求？",
    options: ["诚实、公平、勤勉地行事，维护客户最佳利益及市场廉正", "只要交易盈利便无需考虑程序", "客户是机构便可忽略利益冲突", "内部销售目标优先于客户指示"],
    answer: 0,
    explanation: "诚实公平、勤勉、能力、客户资料、利益冲突及高级管理层责任均是核心操守原则。",
    trap: "把业绩结果当成程序合规的替代品。",
    salesHook: "适用于每一笔机构订单与客户沟通。",
  },
  {
    id: "P1-030",
    topic: 5,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "客户原本只询问某股票的公开流动性数据，销售随后主动表示该股票非常适合客户的低风险授权，并鼓励马上买入。最合适的合规判断是什么？",
    options: ["仍必然只是纯执行", "公开资料永远不可能构成招揽", "该沟通已很可能构成招揽或建议，应按客户资料评估适合性并保留依据", "只要不出具书面报告便无须考虑适合性"],
    answer: 2,
    explanation: "适合性责任看沟通的实质；针对客户情况主动鼓励交易很可能超越事实资料或纯执行。",
    trap: "认为口头沟通或使用公开资料不会触发 suitability。",
    salesHook: "区分 colour、factual execution update 与 recommendation。",
  },
  {
    id: "P1-031",
    topic: 5,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于认识你的客户 KYC：I. 应了解客户身份及指示来源；II. 提供意见时应取得与财务状况、经验和目标相关的资料；III. 资料应按需要更新；IV. 对机构客户可完全依赖销售人员记忆而不保存纪录。哪些陈述正确？",
    options: ["I、II", "I、II、III", "II、IV", "I、III、IV"],
    answer: 1,
    explanation: "I 至 III 正确；机构客户也需要有适当且可核查的 KYC 资料，具体豁免须另行满足条件。",
    trap: "把机构名称或 salesperson familiarity 当成完整 KYC。",
    salesHook: "适用于 fund mandate、authorised trader 与 beneficial owner 核查。",
  },
  {
    id: "P1-032",
    topic: 5,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "关于 best execution，哪项最准确？",
    options: ["永远只比较名义成交价", "采取合理步骤在整体可用条件下争取最佳执行，并考虑适当的价格、成本、速度及成交可能性等因素", "只要使用最大交易所便自动满足", "机构客户永远不能约定具体执行指示"],
    answer: 1,
    explanation: "最佳执行不是机械地只看一个价格；客户具体指示及整体交易条件均可能相关。",
    trap: "把 best execution 等同于每次都取得全市场最低或最高单一价格。",
    salesHook: "Algo、block、high-touch 与 venue selection 的评价基准。",
  },
  {
    id: "P1-033",
    topic: 5,
    difficulty: "基础",
    cognitiveLevel: 2,
    type: "incorrect",
    stem: "关于客户订单优先及处理，以下哪项不正确？",
    options: ["客户订单应按规定得到公平处理", "不能为自身方便不当地压住可执行的客户订单", "法团可在已知客户大额买单后先为自营账户买入，只要稍后仍替客户成交", "订单执行后应及时、公平分配"],
    answer: 2,
    explanation: "利用客户订单信息抢先进行自营交易会产生严重优先次序和利益冲突问题。",
    trap: "认为最终也替客户成交便能补救 front-running。",
    salesHook: "直接对应 institutional flow information 与 prop/facilitation desk 边界。",
  },
  {
    id: "P1-034",
    topic: 5,
    difficulty: "较难",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "券商拟以自有库存向客户完成一笔 facilitation trade。最适当的做法是什么？",
    options: ["把交易描述为纯代理以免客户追问", "清楚管理并披露有关主事人或 facilitation 身份和冲突，取得适用同意，并确保客户获公平对待", "先成交，只有客户亏损才披露", "允许持仓交易员查看客户所有保密订单"],
    answer: 1,
    explanation: "客户 facilitation 涉及中介作为对手方及信息优势，应有身份披露、同意、信息屏障、监督及公平对待。",
    trap: "把 principal risk-taking 隐藏在 agency 语言下。",
    salesHook: "最贴近 institutional equity facilitation 的操守考点。",
  },
  {
    id: "P1-035",
    topic: 5,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "single",
    stem: "一个汇总订单只获部分成交，多个客户均参与。哪项分配方式最合适？",
    options: ["按预先确立的公平方法及时分配，不根据成交后价格表现挑选客户", "把最佳部分留给佣金最高客户", "先看收市价，再决定分给谁", "先分给职员账户，再分客户"],
    answer: 0,
    explanation: "成交应及时及公平分配，不能运用事后信息 cherry-pick。",
    trap: "把商业价值或事后表现作为分配依据。",
    salesHook: "Block order 与 partial fill 的日常场景。",
  },
  {
    id: "P1-036",
    topic: 5,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于订单纪录：I. 应及时记录及标示收到指示的时间；II. 纪录应能识别指示来源、内容及后续处理；III. 通讯渠道应符合获批准的录音及留痕控制；IV. 销售可在数日后凭记忆重建全部订单。哪些陈述正确？",
    options: ["I、II", "II、IV", "I、II、III", "I、III、IV"],
    answer: 2,
    explanation: "订单必须形成及时、可靠和可审计的记录；事后凭记忆补写不能替代正式控制。",
    trap: "认为机构客户关系熟悉便可使用无留痕渠道。",
    salesHook: "电话、聊天工具及 off-channel order 的现实风险。",
  },
  {
    id: "P1-037",
    topic: 5,
    difficulty: "较难",
    cognitiveLevel: 3,
    type: "single",
    stem: "一名不属于专业投资者的客户在没有销售招揽下，主动要求购买非交易所买卖的复杂产品。最稳妥的监管处理是什么？",
    options: ["因属主动要求便无需任何产品审查", "只需说明产品名称", "只要客户签免责书便可成交", "进行产品尽职审查，按复杂产品规则评估适合性，并提供所需产品资料及警告"],
    answer: 3,
    explanation: "复杂产品有额外销售要求；在没有招揽的情况下，也不能简单以 execution-only 标签跳过适用的适合性、披露及警告责任。",
    trap: "把 unsolicited request 当成复杂产品责任的全面豁免。",
    salesHook: "机构业务可用作理解为何客户分类必须先于产品销售判断。",
  },
  {
    id: "P1-038",
    topic: 5,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "客户投诉销售没有按限价指示执行。最适当的处理是什么？",
    options: ["由具适当独立性的人员及时调查录音及订单纪录、向客户回应并纠正系统性问题", "由涉事销售自行删除相关聊天纪录", "若客户仍盈利便不视为投诉", "等监管机构来函后才处理"],
    answer: 0,
    explanation: "投诉应及时、公平处理并保留记录，重大或重复问题还应触发补救及管理层检视。",
    trap: "把盈利与否作为是否存在操守问题的唯一标准。",
    salesHook: "订单争议的标准 response workflow。",
  },
  {
    id: "P1-039",
    topic: 5,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "一家持牌法团拟让新客户全程非亲身开户。最适当的原则是什么？",
    options: ["只要客户上传一张证件照片便必然足够", "采用证监会认可且能可靠核实客户真实完整身份的开户方式，并保存可供合规检查的纪录", "非亲身开户一律被禁止", "客户首次入金后才需要核实身份"],
    answer: 1,
    explanation: "非亲身开户并非一律禁止，但所采用的方法必须属于可接受安排并能可靠核实身份，法团仍须履行 KYC、风险披露及记录责任。",
    trap: "把线上流程的便利性误认为降低身份核实标准。",
    salesHook: "机构及海外客户 onboarding 时，不能用视频或文件上传标签替代 approved approach 检查。",
  },

  {
    id: "P1-040",
    topic: 6,
    difficulty: "基础",
    cognitiveLevel: 2,
    type: "single",
    stem: "高级管理层把所有合规工作外判后，声称法团已不再承担内部监控责任。哪项正确？",
    options: ["外判会自动转移全部监管责任", "高级管理层仍须确保有足够资源、监督、风险管理和有效内部控制", "只有合规部门对控制失败负责", "只要供应商知名便无需监督"],
    answer: 1,
    explanation: "职能可外判，但法团及高级管理层对业务、风险及控制的责任不能一并外判。",
    trap: "把 outsourcing 与 regulatory accountability 混为一谈。",
    salesHook: "交易系统、录音、KYC vendor 均常由外部供应商支持。",
  },
  {
    id: "P1-041",
    topic: 6,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于 AML/CFT 风险为本方法：I. 风险较高的客户或交易通常需要加强尽职审查及监察；II. 风险评估应考虑客户、产品、地域及交付渠道等因素；III. 客户关系建立后仍须持续监察；IV. 低风险客户自动永久免除客户尽职审查。哪些陈述正确？",
    options: ["I、II", "I、IV", "I、II、III", "II、III、IV"],
    answer: 2,
    explanation: "风险为本方法调整措施的程度和频率，但不等于把低风险客户永久排除在法定 CDD 之外。",
    trap: "把 simplified measures 误解为 no measures。",
    salesHook: "大型机构、离岸基金和复杂持股结构仍需按风险评估。",
  },
  {
    id: "P1-042",
    topic: 6,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "一家长期机构客户突然要求把证券出售所得汇给与其没有明显关系的第三方。最适当的第一组行动是什么？",
    options: ["因客户历史悠久便直接执行", "核实指示及第三方关系，比较客户画像和历史交易，进行风险升级，并在形成怀疑时按程序提交可疑交易报告", "立即告诉客户将被举报", "先把款项汇出，再在年末复核"],
    answer: 1,
    explanation: "不寻常第三方付款是重要红旗，应查询、评估、加强监察和内部升级；达到怀疑门槛时向 JFIU 报告。",
    trap: "把长期关系当成无需 AML 审查的理由。",
    salesHook: "Institutional settlement instruction 的典型 AML 场景。",
  },
  {
    id: "P1-043",
    topic: 6,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "当法团形成洗钱或恐怖分子资金筹集怀疑时，哪项处理最正确？",
    options: ["向客户预告即将提交报告", "在社交媒体提醒其他券商", "按内部程序及时向联合财富情报组提交可疑交易报告，并避免 tipping-off", "只有交易已证明为犯罪所得才可报告"],
    answer: 2,
    explanation: "报告基于知识或怀疑，不要求先取得刑事定罪；报告及调查信息须妥善保密。",
    trap: "认为必须有确凿犯罪证据，或可向客户披露报告。",
    salesHook: "销售发现资金或账户行为异常时的明确升级路径。",
  },
  {
    id: "P1-044",
    topic: 6,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "法团使用第三方算法替客户自动执行股票订单。以下哪项最准确？",
    options: ["法团仍须理解系统、进行测试和监察，并维持容量、安全、异常处理及业务连续性控制", "算法由供应商开发，所以法团无需负责", "只有发生客户损失后才需要测试", "算法交易不需要订单记录"],
    answer: 0,
    explanation: "电子交易控制应覆盖治理、测试、部署、监察、容量、保安及事故处理，使用供应商不消除法团责任。",
    trap: "把 vendor model 当成责任转移。",
    salesHook: "Algo wheel、DMA 与 client execution platform 的核心控制。",
  },
  {
    id: "P1-045",
    topic: 6,
    difficulty: "较难",
    cognitiveLevel: 2,
    type: "incorrect",
    stem: "关于另类流通量资金池 ALP，以下哪项不正确？",
    options: ["营运者应有适当准入、监察及公平有序运作控制", "应保护客户及交易资料的机密性", "所有使用者必须实时看到其他参与者的完整身份和全部订单意图", "系统及路由安排应受适当管理和监督"],
    answer: 2,
    explanation: "ALP 的核心之一是妥善保护资料及管理访问，不要求向所有参与者公开完整身份和订单意图。",
    trap: "把透明监管等同于向市场参与者公开保密订单信息。",
    salesHook: "Dark pool 或 internal crossing 的信息隔离。",
  },
  {
    id: "P1-046",
    topic: 6,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "销售拟把机构客户账户的详细持仓、交易记录及联系人资料交给发行人 IR 团队，以换取 corporate access 名额。最适当的处理是什么？",
    options: ["客户是机构便可自由分享", "停止并评估保密责任、收集及使用目的、客户通知或同意、资料最小化及适用法律依据", "删除客户名称后便一定没有私隐风险", "只要用公司邮箱便可发送"],
    answer: 1,
    explanation: "客户账户资料受保密及内部使用控制；涉及可识别自然人的联系人资料时还须考虑个人资料要求。简单去名或机构客户身份都不会自动排除风险。",
    trap: "认为 institutional account 数据天然不受私隐或保密约束。",
    salesHook: "Corporate access 与 client intelligence sharing 的现实边界。",
  },
  {
    id: "P1-047",
    topic: 6,
    difficulty: "较难",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于共同汇报标准 CRS：I. 其目的包括通过税务管辖区之间交换金融账户资料提高税务透明度；II. 金融机构须进行尽职审查以识别有关账户及税务居民身份；III. CRS 不能替代 AML 客户尽职审查；IV. 每一个香港客户都必然向所有海外税务机关汇报。哪些陈述正确？",
    options: ["I、II", "II、IV", "I、II、III", "I、III、IV"],
    answer: 2,
    explanation: "CRS 有特定尽职审查、可汇报账户及参与管辖区框架，不是把所有客户资料无差别发送给所有国家。",
    trap: "把税务信息交换理解为全球无限制披露，或与 AML 混为一项。",
    salesHook: "机构开户时常同时收集 AML 与 tax residency 文件。",
  },
  {
    id: "P1-048",
    topic: 6,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "券商的主要订单管理系统在交易时段突然中断。最适当的业务连续性处理是什么？",
    options: ["让销售人员用任何私人通讯工具继续接单，不必留痕", "启动经测试的应变及恢复计划，保护客户和市场、使用获批准的替代流程、保存纪录并及时升级事故", "等待系统自行恢复，期间不通知任何负责人员", "删除未完成订单以免产生投诉"],
    answer: 1,
    explanation: "有效的业务连续性安排应覆盖事故识别、获批准的替代处理、数据及订单完整性、通讯、升级、恢复和事后检视，并须定期测试。",
    trap: "把业务连续性误解为可以暂时放弃订单记录、客户保护或内部监督。",
    salesHook: "OMS、录音或市场连接故障时，sales 必须知道 approved fallback 而非临时 improvisation。",
  },

  {
    id: "P1-049",
    topic: 7,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "incorrect",
    stem: "关于交易所和结算所，以下哪项不正确？",
    options: ["交易所提供交易市场并执行相应交易规则", "结算所进行结算、交收及相关风险管理", "结算所负责向客户提供个股买卖建议", "交易参与者须遵守适用的交易所规则"],
    answer: 2,
    explanation: "结算所的核心是 post-trade 结算交收和风险管理，不是向投资者提供证券意见。",
    trap: "混淆交易、结算、经纪和投资意见角色。",
    salesHook: "向客户解释 execution venue 与 clearing venue。",
  },
  {
    id: "P1-050",
    topic: 7,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "关于沪深港通等互联互通安排，哪项最准确？",
    options: ["通过指定基础设施提供跨境市场互联，交易仍受适用市场规则、资格及额度等安排约束", "投资者可绕过所有两地法律", "所有证券从上市首日起自动纳入", "互联互通把两地交易所合并成同一法人"],
    answer: 0,
    explanation: "互联互通是有特定规则和基础设施的跨境市场准入机制，不消除两地监管边界。",
    trap: "把 market access 误解为完全监管一体化。",
    salesHook: "Northbound/Southbound institutional order 的基础框架。",
  },
  {
    id: "P1-051",
    topic: 7,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "联交所因若干股票推出每周期权合约而更新相关庄家安排。以下哪项最准确？",
    options: ["期权买卖交易所参与者可向联交所申请，就特定期权类别及指定到期期限（如适用）担任庄家；联交所可评估其资格", "任何交易所参与者均自动成为所有期权类别的庄家", "庄家资格只由发行人授予，与联交所无关", "一经获批成为庄家，便可在所有期权类别和到期期限报价而无需指定范围"],
    answer: 0,
    explanation: "v3.5 的考试口径落在庄家获批范围：申请会指定期权类别及到期期限（如适用），联交所可在批准前评估申请人的资格。",
    trap: "把庄家许可理解为自动取得、由发行人授予，或覆盖全部期权类别和期限。",
    salesHook: "客户询问新到期期限的流动性时，先分清产品可交易性与庄家获批报价范围。",
  },
  {
    id: "P1-052",
    topic: 7,
    difficulty: "中等",
    cognitiveLevel: 2,
    type: "single",
    stem: "以下哪项市场与结算安排配对最恰当？",
    options: ["SEHK 股票期权由 HKCC 结算；HKFE 期货由 HKSCC 结算", "SEHK 股票期权由 SEOCH 结算；HKFE 期货由 HKCC 结算", "所有产品均只由 SEHK 自行结算", "股票期权和期货均不经认可结算所"],
    answer: 1,
    explanation: "SEHK 期权市场的结算所为 SEOCH，HKFE 期货及期权由 HKCC 结算。",
    trap: "把 HKSCC、SEOCH 与 HKCC 的产品范围混淆。",
    salesHook: "衍生工具客户开户及结算安排的基础知识。",
  },
  {
    id: "P1-053",
    topic: 7,
    difficulty: "较难",
    cognitiveLevel: 2,
    type: "combination",
    stem: "关于衍生工具持仓限额及大额未平仓合约汇报：I. 除获授权例外，任何人持有或控制的指定合约不得超过订明上限；II. 达到须申报水平时，应在开始持有或控制当日后的一个营业日内书面通知有关交易所；III. 任何人可通过多个账户分拆持仓规避合计限额；IV. 限额及汇报有助监管集中和市场风险。哪些陈述正确？",
    options: ["I、II", "I、III", "II、III、IV", "I、II、IV"],
    answer: 3,
    explanation: "I、II、IV 正确；达到须申报水平后须按规定及时通知有关交易所，也不得以分拆账户等方式规避持仓限额或汇报要求。",
    trap: "把每个账户当成完全独立而忽略法定合计或控制规则。",
    salesHook: "Equity derivatives 或 index futures 客户的 position monitoring。",
  },
  {
    id: "P1-054",
    topic: 7,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "销售向客户推广一只在 SEHK 上市的衍生权证。最合适的表述是什么？",
    options: ["上市代表发行人保证客户不会亏损", "以公平、不误导和风险均衡的方式说明条款、杠杆、流通性及发行人信用风险", "只展示潜在最高回报", "称其为股票替代品即可省略产品风险"],
    answer: 1,
    explanation: "上市结构性产品仍有杠杆、到期、流通性及发行人信用等风险，推广材料不得误导。",
    trap: "把 listing status 当成产品安全认证。",
    salesHook: "Institutional idea pitch 也须保持 risk-balanced communication。",
  },

  {
    id: "P1-055",
    topic: 8,
    difficulty: "基础",
    cognitiveLevel: 1,
    type: "single",
    stem: "《上市规则》的主要目的最接近以下哪项？",
    options: ["通过持续披露、资格及交易规则支持公平有序的上市市场和投资者保障", "保证所有新股上市后上涨", "为发行人免除公司法责任", "允许控股股东不披露重大交易"],
    answer: 0,
    explanation: "上市规则关注市场质量、披露、发行人及相关人士责任，并不保证证券表现。",
    trap: "把上市审批误解为投资价值背书。",
    salesHook: "向客户介绍 IPO 时必须区分上市资格与投资建议。",
  },
  {
    id: "P1-056",
    topic: 8,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "IPO 保荐人发现发行人管理层提供的关键收入数据与外部资料明显不一致。最适当的做法是什么？",
    options: ["只要董事签署确认便无需再查", "进行独立及充分的尽职审查，解决重大不一致，并在无法得到合理解释时升级或暂停程序", "等上市后由投资者自行发现", "删除外部资料以保持文件一致"],
    answer: 1,
    explanation: "保荐人须进行独立尽职审查，不能把责任完全转移给发行人声明。",
    trap: "把 management representation 当成 due diligence 的替代品。",
    salesHook: "销售在 pre-deal education 中不可把 sponsor presence 描述为收益保证。",
  },
  {
    id: "P1-057",
    topic: 8,
    difficulty: "较难",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "上市公司拟向其董事控制的实体收购重大资产。最恰当的第一项监管分析是什么？",
    options: ["董事认识交易对手，所以不受上市规则约束", "只看交易是否盈利", "识别是否构成关连交易及须予公布交易，并评估披露、独立股东批准及回避等要求", "只要用现金支付便不需公告"],
    answer: 2,
    explanation: "同一交易可同时触发交易规模分类及关连人士规则，应在签约或执行前完成分析。",
    trap: "认为商业合理性或付款方式会自动排除规则。",
    salesHook: "Event-driven sales 需理解交易为何可能停牌、公告或交股东表决。",
  },

  {
    id: "P1-058",
    topic: 9,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "most_likely",
    stem: "上市公司 CFO 在闭门会中向销售透露尚未公布、很可能显著影响股价的盈利数据。销售最适当的行动是什么？",
    options: ["立即告诉最重要的客户先买入", "停止使用或传播该资料，保存记录并立即向合规升级，遵守信息屏障和交易限制", "只要不亲自买入便可向客户转述", "先发给研究分析员确认是否准确"],
    answer: 1,
    explanation: "重大非公开信息可能构成内幕消息；不得交易、建议交易或向无正当需要者泄露，应立即升级和限制。",
    trap: "认为不在个人账户交易便可 tip clients。",
    salesHook: "Corporate access 与 earnings call 的最高频风险。",
  },
  {
    id: "P1-059",
    topic: 9,
    difficulty: "中等",
    cognitiveLevel: 3,
    type: "single",
    stem: "客户要求券商在其两个受控账户之间反复对敲，目的只是制造某股票成交活跃的假象。最适当的处理是什么？",
    options: ["客户拥有两个账户便可执行", "只要不改变客户最终持仓便没有问题", "拒绝并向合规升级，因为有关安排可能构成虚假交易或其他市场失当", "把订单拆小后执行即可"],
    answer: 2,
    explanation: "没有真实经济目的、旨在制造虚假成交或流通量表象的对敲可能构成 false trading。",
    trap: "把最终净持仓不变误认为没有市场影响。",
    salesHook: "识别 wash trade 与 matched order。",
  },
  {
    id: "P1-060",
    topic: 9,
    difficulty: "较难",
    cognitiveLevel: 3,
    type: "single",
    stem: "某基金要求交易员在收市前以极小订单反复推高价格，以改善其月末估值。该行为最可能涉及什么问题？",
    options: ["价格操纵或人为影响收市价的失当交易", "正常的 best execution", "合法的股息调整", "纯粹的账户记录问题"],
    answer: 0,
    explanation: "以非真实投资目的在关键时点影响价格或估值，可能属于 marking the close、价格操纵或相关市场失当。",
    trap: "订单金额小不代表不会影响市场价格形成。",
    salesHook: "收市盘、NAV marking 与 benchmark execution 的风险。",
  },
];
